In [29]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

In [30]:
df = pd.read_csv("SupplyChainGHGEmissionFactors_v1.3.0_NAICS_byGHG_USD2022.csv")

In [31]:
df.head()

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,HFC-23,"kg/2022 USD, purchaser price",3.230000e-09,1.340000e-09,4.570000e-09,1111A0
1,111110,Soybean Farming,Carbon dioxide,"kg/2022 USD, purchaser price",1.340000e-01,3.780000e-02,1.720000e-01,1111A0
2,111110,Soybean Farming,HFC-236fa,"kg/2022 USD, purchaser price",1.440000e-10,2.020000e-10,3.450000e-10,1111A0
3,111110,Soybean Farming,Carbon tetrafluoride,"kg/2022 USD, purchaser price",5.130000e-09,5.970000e-09,1.110000e-08,1111A0
4,111110,Soybean Farming,HFC-32,"kg/2022 USD, purchaser price",3.000000e-08,4.200000e-08,7.200000e-08,1111A0

In [32]:
df.columns

Index(['2017 NAICS Code', '2017 NAICS Title', 'GHG', 'Unit',
       'Supply Chain Emission Factors without Margins',
       'Margins of Supply Chain Emission Factors',
       'Supply Chain Emission Factors with Margins', 'Reference USEEIO Code'],
      dtype='str')

In [33]:
df.shape

(18288, 8)

In [34]:
df.describe()

,2017 NAICS Code,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins
count,18288.000000,1.828800e+04,1.828800e+04,1.828800e+04
mean,424917.376969,1.022439e-02,8.167654e-04,1.104055e-02
std,164865.428749,6.376527e-02,5.772884e-03,6.669205e-02
min,111110.000000,1.970000e-11,0.000000e+00,1.970000e-11
25%,325588.250000,1.330000e-09,0.000000e+00,1.580000e-09
50%,423700.000000,1.420000e-08,0.000000e+00,1.650000e-08
75%,532111.250000,3.387500e-07,1.610000e-09,3.500000e-07
max,813990.000000,3.790000e+00,1.090000e-01,3.860000e+00

In [36]:
X = df.iloc[:, 4:6].values
y = df.iloc[:,6].values

In [38]:
print(X)

[[3.23e-09 1.34e-09]
 [1.34e-01 3.78e-02]
 [1.44e-10 2.02e-10]
 ...
 [1.32e-09 0.00e+00]
 [9.39e-02 0.00e+00]
 [6.64e-03 0.00e+00]]

In [39]:
print(y)

[4.57e-09 1.72e-01 3.45e-10 ... 1.32e-09 9.39e-02 6.64e-03]

In [37]:
#Training features: splits dataset into test set and training set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)